[module]
name = "ip"
dependencies = [
    "misc/md5",
    "misc/hook",
    "misc/neti",
    "misc/cc",
    "cc/cc_sunreno",
    "cc/cc_newreno",
    "cc/cc_cubic",
    "crypto/swrand",
]
src = [
    # icmp
    "icmp.c",
    "icmp_opt_data.c",
    # rts
    "rts.c",
    "rts_opt_data.c",
    # tcp
    "../tcp/tcp.c",
    "../tcp/tcp_fusion.c",
    "../tcp/tcp_opt_data.c",
    "../tcp/tcp_sack.c",
    "../tcp/tcp_stats.c",
    "../tcp/tcp_misc.c",
    "../tcp/tcp_timers.c",
    "../tcp/tcp_time_wait.c",
    "../tcp/tcp_tpi.c",
    "../tcp/tcp_output.c",
    "../tcp/tcp_input.c",
    "../tcp/tcp_socket.c",
    "../tcp/tcp_bind.c",
    "../tcp/tcp_cluster.c",
    "../tcp/tcp_tunables.c",
    # udp
    "../udp/udp.c",
    "../udp/udp_opt_data.c",
    "../udp/udp_tunables.c",
    "../udp/udp_stats.c",
    # sctp
    "../sctp/sctp.c",
    "../sctp/sctp_opt_data.c",
    "../sctp/sctp_output.c",
    "../sctp/sctp_init.c",
    "../sctp/sctp_input.c",
    "../sctp/sctp_cookie.c",
    "../sctp/sctp_conn.c",
    "../sctp/sctp_error.c",
    "../sctp/sctp_snmp.c",
    "../sctp/sctp_tunables.c",
    "../sctp/sctp_shutdown.c",
    "../sctp/sctp_common.c",
    "../sctp/sctp_timer.c",
    "../sctp/sctp_heartbeat.c",
    "../sctp/sctp_hash.c",
    "../sctp/sctp_bind.c",
    "../sctp/sctp_notify.c",
    "../sctp/sctp_asconf.c",
    "../sctp/sctp_addr.c",
    "../sctp/sctp_misc.c",
    "tn_ipopt.c",
    "tnet.c",
    "ip_netinfo.c",
    # ilb
    "../ilb/ilb.c",
    "../ilb/ilb_nat.c",
    "../ilb/ilb_conn.c",
    "../ilb/ilb_alg_hash.c",
    "../ilb/ilb_alg_rr.c",
    # comm
    "../../../../common/inet/inet_hash.c",
    # ip
    "igmp.c",
    "ipmp.c",
    "ip.c",
    "ip6.c",
    "ip6_asp.c",
    "ip6_if.c",
    "ip6_ire.c",
    "ip6_rts.c",
    "ip_if.c",
    "ip_ire.c",
    "ip_listutils.c",
    "ip_mroute.c",
    "ip_multi.c",
    "ip2mac.c",
    "ip_ndp.c",
    "ip_rts.c",
    "ip_srcid.c",
    "ipddi.c",
    "ipdrop.c",
    "../mi.c",
    "../nd.c",
    "../tunables.c",
    "../optcom.c",
    "../snmpcom.c",
    "ipsec_loader.c",
    "spd.c",
    "ipclassifier.c",
    "../inet_common.c",
    "ip_squeue.c",
    "../squeue.c",
    "ip_sadb.c",
    "ip_ftable.c",
    "../proto_set.c",
    "../../../../common/net/patricia/radix.c",
    "ip_dummy.c",
    "ip_helper_stream.c",
    "ip_tunables.c",
    "ip_output.c",
    "ip_input.c",
    "ip6_input.c",
    "ip6_output.c",
    "ip_arp.c",
    "conn_opt.c",
    "ip_attr.c",
    "ip_dce.c",
    # ddm
    "ddm.c",
]
