[genunix]

# definitions to pass to compiler
BOOTBANNER1 = '" ^o Version ^v ^w-bit"'
BOOTBANNER2 = '""'
BOOTBANNER3 = '""'
BOOTBANNER4 = '""'
BOOTBANNER5 = '""'

src = [
    "syscall/access.c",
    "syscall/acl.c",
    "../../common/acl/acl_common.c",
    "syscall/adjtime.c",
    "syscall/alarm.c",
    "os/aio_subr.c",
    "syscall/auditsys.c",
    "os/audit_core.c",
    "os/audit_zone.c",
    "os/audit_memory.c",
    "os/autoconf.c",
    "../../common/avl/avl.c",
    "os/bdev_dsort.c",
    "os/bio.c",
    "../../common/bitext/bitext.c",
    "../../common/bootbanner/bootbanner.c",
    "os/bitmap.c",
    "../../common/tsol/blabel.c",
    "syscall/brandsys.c",
    "../../common/bzip2/blocksort.c",
    "../../common/bzip2/compress.c",
    "../../common/bzip2/decompress.c",
    "../../common/bzip2/randtable.c",
    "../../common/bzip2/bzlib.c",
    "../../common/bzip2/crctable.c",
    "../../common/bzip2/huffman.c",
    "os/callb.c",
    "os/callout.c",
    "syscall/chdir.c",
    "syscall/chmod.c",
    "syscall/chown.c",
    "syscall/cladm.c",
    "disp/class.c",
    "os/clock.c",
    "os/clock_highres.c",
    "os/clock_process.c",
    "os/clock_realtime.c",
    "os/clock_thread.c",
    "syscall/close.c",
    "os/compress.c",
    "os/condvar.c",
    "io/conf.c",
    "os/console.c",
    "os/contract.c",
    "os/copyops.c",
    "os/core.c",
    "syscall/corectl.c",
    "os/cred.c",
    "pcmcia/cs/cs_stubs.c",
    "os/dacf.c",
    "os/dacf_clnt.c",
    "os/damap.c",
    "os/cyclic.c",
    "os/ddi.c",
    "os/ddifm.c",
    "os/ddi_hp_impl.c",
    "os/ddi_hp_ndi.c",
    "os/ddi_intr.c",
    "os/ddi_intr_impl.c",
    "os/ddi_intr_irm.c",
    "os/ddi_nodeid.c",
    "os/ddi_periodic.c",
    "os/ddi_ufm.c",
    "os/devcfg.c",
    "os/devcache.c",
    "contract/device.c",
    "../../common/devid/devid.c",
    "../../common/devid/devid_scsi.c",
    "../../common/devid/devid_smp.c",
    "os/devid_cache.c",
    "os/devpolicy.c",
    "disp/disp_lock.c",
    "os/dkioc_free_util.c",
    "fs/dnlc.c",
    "os/driver.c",
    "os/dumpsubr.c",
    "os/driver_lyr.c",
    "os/dtrace_subr.c",
    "os/errorq.c",
    "io/etheraddr.c",
    "os/evchannels.c",
    "os/exacct.c",
    "../../common/exacct/exacct_core.c",
    "os/exec.c",
    "os/exit.c",
    "os/fbio.c",
    "syscall/fcntl.c",
    "fs/fdbuffer.c",
    "syscall/fdsync.c",
    "fs/fem.c",
    "../../common/util/ffs.c",
    "os/fio.c",
    "os/firmload.c",
    "os/flock.c",
    "os/fm.c",
    "os/fork.c",
    "vm/vpm.c",
    "../../common/fsreparse/fs_reparse.c",
    "fs/fs_subr.c",
    "fs/fsflush.c",
    "os/ftrace.c",
    "syscall/getcwd.c",
    "syscall/getdents.c",
    "syscall/getloadavg.c",
    "syscall/getpagesizes.c",
    "syscall/getpid.c",
    "fs/gfs.c",
    "syscall/rusagesys.c",
    "syscall/gid.c",
    "syscall/groups.c",
    "os/grow.c",
    "vm/hat_refmod.c",
    "os/id32.c",
    "../../common/idspace/id_space.c",
    "inet/ip/inet_ntop.c",
    "os/instance.c",
    "syscall/ioctl.c",
    "os/ip_cksum.c",
    "syscall/issetugid.c",
    "ipp/ippconf.c",
    "os/kcpc.c",
    "os/kdi.c",
    "os/kiconv.c",
    "os/klpd.c",
    "os/kmem.c",
    "os/ksensor.c",
    "os/ksyms_snapshot.c",
    "io/l_strplumb.c",
    "os/labelsys.c",
    "syscall/link.c",
    "../../common/list/list.c",
    "os/lockstat_subr.c",
    "os/log_sysevent.c",
    "os/logsubr.c",
    "fs/lookup.c",
    "syscall/lseek.c",
    "../../common/tsol/ltos.c",
    "os/lwp.c",
    "syscall/lwp_create.c",
    "syscall/lwp_info.c",
    "syscall/lwp_self.c",
    "syscall/lwp_sobj.c",
    "syscall/lwp_timer.c",
    "syscall/lwpsys.c",
    "os/main.c",
    "syscall/mmapobjsys.c",
    "syscall/memcntl.c",
    "../../common/util/memstr.c",
    "syscall/lgrpsys.c",
    "syscall/mkdir.c",
    "syscall/mknod.c",
    "syscall/mount.c",
    "os/move.c",
    "os/msacct.c",
    "fs/nbmlock.c",
    "os/ndifm.c",
    "syscall/nice.c",
    "os/netstack.c",
    "syscall/ntptime.c",
    "../../common/nvpair/nvpair.c",
    "os/nvpair_alloc_system.c",
    "../../common/nvpair/nvpair_alloc_fixed.c",
    "../../common/nvpair/fnvpair.c",
    "../../common/net/dhcp/octet.c",
    "syscall/open.c",
    "syscall/p_online.c",
    "syscall/pathconf.c",
    "fs/pathname.c",
    "syscall/pause.c",
    "os/serializer.c",
    "io/pci_intr_lib.c",
    "io/pci_cap.c",
    "os/pcifm.c",
    "os/pgrp.c",
    "syscall/pgrpsys.c",
    "os/pid.c",
    "fs/pkp_hash.c",
    "os/policy.c",
    "syscall/poll.c",
    "os/pool.c",
    "os/pool_pset.c",
    "os/port_subr.c",
    "syscall/ppriv.c",
    "os/printf.c",
    "disp/priocntl.c",
    "os/priv.c",
    #"os/priv_const.c",
    "os/proc.c",
    "syscall/psecflags.c",
    "os/procset.c",
    "syscall/processor_bind.c",
    "syscall/processor_info.c",
    "syscall/profil.c",
    "os/project.c",
    "../../common/util/qsort.c",
    "syscall/getrandom.c",
    "os/rctl.c",
    "syscall/rctlsys.c",
    "syscall/readlink.c",
    "refhash/refhash.c",
    "os/refstr.c",
    "syscall/rename.c",
    "syscall/resolvepath.c",
    "os/retire_store.c",
    "contract/process.c",
    "syscall/rlimit.c",
    "os/rmap.c",
    "syscall/rw.c",
    "os/rwstlock.c",
    "io/sad_conf.c",
    "os/sid.c",
    "syscall/sidsys.c",
    "os/sched.c",
    "os/schedctl.c",
    "os/sctp_crc32.c",
    "../../common/secflags/secflags.c",
    "vm/seg_dev.c",
    "vm/seg_hole.c",
    "vm/seg_kp.c",
    "vm/seg_kpm.c",
    "vm/seg_map.c",
    "vm/seg_vn.c",
    "vm/seg_spt.c",
    "vm/seg_umap.c",
    "os/semaphore.c",
    "syscall/sendfile.c",
    "os/session.c",
    "os/share.c",
    "disp/shuttle.c",
    "os/sig.c",
    "syscall/sigaction.c",
    "syscall/sigaltstack.c",
    "syscall/signotify.c",
    "syscall/sigpending.c",
    "syscall/sigprocmask.c",
    "syscall/sigqueue.c",
    "syscall/sigsendset.c",
    "syscall/sigsuspend.c",
    "syscall/sigtimedwait.c",
    "os/sleepq.c",
    "io/sock_conf.c",
    "os/space.c",
    "../../common/util/sscanf.c",
    "syscall/stat.c",
    "syscall/statfs.c",
    "syscall/statvfs.c",
    "../../common/tsol/stol.c",
    "io/str_conf.c",
    "syscall/strcalls.c",
    "io/stream.c",
    "os/streamio.c",
    "os/strext.c",
    "os/strsubr.c",
    "io/strsun.c",
    "os/subr.c",
    "os/sunddi.c",
    "os/sunmdi.c",
    "os/sunndi.c",
    "os/sunpci.c",
    "os/sunpm.c",
    "io/sundlpi.c",
    "io/suntpi.c",
    "fs/swapfs/swap_subr.c",
    "fs/swapfs/swap_vnops.c",
    "syscall/symlink.c",
    "syscall/sync.c",
    "disp/sysclass.c",
    "syscall/sysconfig.c",
    "os/sysent.c",
    "syscall/sysfs.c",
    "syscall/systeminfo.c",
    "os/task.c",
    "os/taskq.c",
    "syscall/tasksys.c",
    "syscall/time.c",
    "os/timer.c",
    "syscall/times.c",
    "os/timers.c",
    "disp/thread.c",
    "os/tlabel.c",
    "os/turnstile.c",
    "io/tty_common.c",
    "../../common/unicode/u8_textprep.c",
    "syscall/uadmin.c",
    "../../common/unicode/uconv.c",
    "syscall/ucredsys.c",
    "syscall/uid.c",
    "syscall/umask.c",
    "syscall/umount.c",
    "syscall/uname.c",
    "os/unix_bb.c",
    "syscall/unlink.c",
    "os/upanic.c",
    "os/urw.c",
    "syscall/utime.c",
    "syscall/utssys.c",
    "syscall/uucopy.c",
    "fs/vfs.c",
    "os/vfs_conf.c",
    "os/vmem.c",
    "vm/vm_anon.c",
    "vm/vm_as.c",
    "os/vm_meter.c",
    "os/vm_pageout.c",
    "vm/vm_pvn.c",
    "vm/vm_rm.c",
    "vm/vm_seg.c",
    "os/vm_subr.c",
    "vm/vm_swap.c",
    "vm/vm_usage.c",
    "fs/vnode.c",
    "io/vuid_queue.c",
    "io/vuid_store.c",
    "os/waitq.c",
    "os/watchpoint.c",
    "syscall/yield.c",
    "io/scsi/conf/scsi_confdata.c",
    "fs/xattr.c",
    "../../common/xattr/xattr_common.c",
    "rpc/xdr_mblk.c",
    "rpc/xdr_mem.c",
    "rpc/xdr.c",
    "rpc/xdr_array.c",
    "rpc/xdr_refer.c",
    "os/zone.c",
    # Intel specific
    "../intel/os/archdep.c",
    "../intel/syscall/getcontext.c",
    "../intel/syscall/install_utrap.c",
    "../intel/syscall/lwp_private.c",
    "../intel/promif/prom_enter.c",
    "../intel/promif/prom_exit.c",
    "../intel/promif/prom_panic.c",
    "../intel/os/sendsig.c",
    "../intel/os/syscall.c",
    "../intel/promif/prom_env.c",
	"../intel/promif/prom_emul.c",
	"../intel/promif/prom_getchar.c",
	"../intel/promif/prom_init.c",
	"../intel/promif/prom_node.c",
	"../intel/promif/prom_printf.c",
	"../intel/promif/prom_prop.c",
	"../intel/promif/prom_putchar.c",
	"../intel/promif/prom_reboot.c",
	"../intel/promif/prom_version.c",
    # NOT_YET_KMODS
    ## OLDPTY_OBJS
    "io/tty_ptyconf.c",
    ## PTY_OBJS
    "io/ptms_conf.c",
    ## VCONS_CONF_OBJS
    "io/vcons_conf.c",
    ## MOD_OBJS
    "os/modctl.c",
    "os/modsubr.c",
    "os/modsysfile.c",
    "os/modconf.c",
    "os/modhash.c",
]
