/*
 * This file and its contents are supplied under the terms of the
 * Common Development and Distribution License ("CDDL"), version 1.0.
 * You may only use this file in accordance with the terms of version
 * 1.0 of the CDDL.
 *
 * A full copy of the text of the CDDL should have accompanied this
 * source.  A copy of the CDDL is also available via the Internet at
 * http://www.illumos.org/license/CDDL.
 */

/*
 * Copyright 2022 Oxide Computer Co.
 */

#ifndef _SYS_IO_HUASHAN_PMIO_H
#define	_SYS_IO_HUASHAN_PMIO_H

/*
 * PMIO is notionally power management, but in fact it's one of several
 * dumping grounds in the FCH covering everything from the hardware
 * implementation of ACPI to decoding control to clock gating to voltage
 * thresholds and much more.  If you're looking for something that in any
 * way controls low-speed functionality, power states, or legacy PC-ish
 * functions that actually appear elsewhere, this is probably a good place to
 * start looking.
 */

#include <sys/types.h>
#include <sys/bitext.h>
#include <sys/io/huashan/fchregs.h>

#ifdef __cplusplus
extern "C" {
#endif

/*
 * XXX Should this be Milan-specific?  It isn't, in practice, and as far as
 * we know every processor with a Huashan FCH has the same addresses for all
 * of this.
 */
#define	FCH_PM_PHYS_BASE			0xfed80300
#define	FCH_PM_SIZE				0x100

#define	FCH_PM_R_DECODEEN_OFFSET		0x00
#define	FCH_PM_R_DECODEEN_WIDTH			32
#define	FCH_PM_R_DECODEEN_F_IOAPICCONFIG	31, 30
#define	FCH_PM_R_DECODEEN_F_HPET_MSI_EN		29, 29
#define	FCH_PM_R_DECODEEN_F_HPET_WIDTH_SEL	28, 28
#define	FCH_PM_R_DECODEEN_F_WDTOPTIONS		27, 26
#define	FCH_PM_R_DECODEEN_F_WDTFREQ		25, 24
#define	FCH_PM_R_DECODEEN_F_ASFCLKSEL		23, 21
#define	FCH_PM_R_DECODEEN_F_SMBUS0SEL		20, 19
#define	FCH_PM_R_DECODEEN_F_ASFCLKSWITCH	18, 18
#define	FCH_PM_R_DECODEEN_F_ASFCLKSTRETCHEN	17, 17
#define	FCH_PM_R_DECODEEN_F_ASFSMMASTEREN	16, 16
#define	FCH_PM_R_DECODEEN_F_SMBUSASFIOBASE	15, 8
#define	FCH_PM_R_DECODEEN_F_WDTEN		7, 7
#define	FCH_PM_R_DECODEEN_F_HPETEN		6, 6
#define	FCH_PM_R_DECODEEN_F_IOAPICEN		5, 5
#define	FCH_PM_R_DECODEEN_F_SMBUSASFIOEN	4, 4
#define	FCH_PM_R_DECODEEN_F_DMAPORT80		3, 3
#define	FCH_PM_R_DECODEEN_F_LEGACYDMAIOEN	2, 2
#define	FCH_PM_R_DECODEEN_F_CF9IOEN		1, 1
#define	FCH_PM_R_DECODEEN_F_LEGACYIOEN		0, 0

#define	FCH_PM_R_ISACONTROL_OFFSET		0x04
#define	FCH_PM_R_ISACONTROL_WIDTH		32
#define	FCH_PM_R_ISACONTROL_F_RTC_BG_ADJ	31, 26
#define	FCH_PM_R_ISACONTROL_F_RTC_BG_SET_EN	25, 25
#define	FCH_PM_R_ISACONTROL_F_RTC_HIGH_RES	24, 24
#define	FCH_PM_R_ISACONTROL_F_RTC_OSC_OP1	21, 21
#define	FCH_PM_R_ISACONTROL_F_RTC_OSC_OP0	20, 20
#define	FCH_PM_R_ISACONTROL_F_RTC_OSC_SET1	19, 19
#define	FCH_PM_R_ISACONTROL_F_RTC_OSC_SET0	18, 18
#define	FCH_PM_R_ISACONTROL_F_RTC_OSC_SET_EN	17, 17
#define	FCH_PM_R_ISACONTROL_F_ABCLKGATEEN	16, 16
#define	FCH_PM_R_ISACONTROL_F_BM_REQ_EN		11, 11
#define	FCH_PM_R_ISACONTROL_F_DRQMASKEN		9, 9
#define	FCH_PM_R_ISACONTROL_F_DMAENHANCEEN	8, 8
#define	FCH_PM_R_ISACONTROL_F_READ_SHADOW	5, 5
#define	FCH_PM_R_ISACONTROL_F_MMIOEN		1, 1
#define	FCH_PM_R_ISACONTROL_F_BIOSRAMEN		0, 0

#define	FCH_PM_R_PCICONTROL_OFFSET		0x08
#define	FCH_PM_R_PCICONTROL_WIDTH		32
#define	FCH_PM_R_PCICONTROL_F_FORCE_SLPSTATE_RETRY	25, 25
#define	FCH_PM_R_PCICONTROL_F_FORCE_STPCLK_RETRY	24, 24
#define	FCH_PM_R_PCICONTROL_F_AB_STALL_EN	23, 23
#define	FCH_PM_R_PCICONTROL_F_SHUTDOWNOPTION	20, 20
#define	FCH_PM_R_PCICONTROL_F_SHUTDOWNOPTION_V_ISSUE_INIT	0
#define	FCH_PM_R_PCICONTROL_F_SHUTDOWNOPTION_V_PCI_RESET	1
#define	FCH_PM_R_PCICONTROL_F_MASTERNOWAIT	19, 19	/* must be 1 */
#define	FCH_PM_R_PCICONTROL_F_ECHOSTFIX		18, 18
#define	FCH_PM_R_PCICONTROL_F_CHANGEDMA		17, 17
#define	FCH_PM_R_PCICONTROL_F_GATEDMA		16, 16
#define	FCH_PM_R_PCICONTROL_F_CLOCK_SLOW_MASK	15, 15
#define	FCH_PM_R_PCICONTROL_F_EXT_INTR_TIME	14, 12
#define	FCH_PM_R_PCICONTROL_F_EXT_INTR_TIME_U_TIME_NS	USEC2NSEC(2)
#define	FCH_PM_R_PCICONTROL_F_DLY_EN		11, 11
#define	FCH_PM_R_PCICONTROL_F_IGNR_USB_SMI_REQ	10, 10
#define	FCH_PM_R_PCICONTROL_F_BLOCK_ACPI_S5_INTR_ST	9, 9
#define	FCH_PM_R_PCICONTROL_F_PIC_APIC_ARBITER	8, 8
#define	FCH_PM_R_PCICONTROL_F_FORCE_SMAF_MATCH	7, 7
#define	FCH_PM_R_PCICONTROL_F_NMIMSGSEL		6, 6
#define	FCH_PM_R_PCICONTROL_F_PICMSGSEL		5, 5
#define	FCH_PM_R_PCICONTROL_F_MSG_INTR_ENABLE	4, 4
#define	FCH_PM_R_PCICONTROL_F_MASK_MSG_BMSTS_EN	3, 3
#define	FCH_PM_R_PCICONTROL_F_FAKE_DMA_EN	2, 2
#define	FCH_PM_R_PCICONTROL_F_UNDO_WRDT_DONE	1, 1
#define	FCH_PM_R_PCICONTROL_F_UNDO_DMA_CHANGE	0, 0

#define	FCH_PM_R_STPCLKSMAF_OFFSET		0x0c
#define	FCH_PM_R_STPCLKSMAF_WIDTH		32
#define	FCH_PM_R_STPCLKSMAF_F_TTSMAF		30, 28
#define	FCH_PM_R_STPCLKSMAF_F_NSSMAF		26, 24
#define	FCH_PM_R_STPCLKSMAF_F_S3SMAF		22, 20
#define	FCH_PM_R_STPCLKSMAF_F_S1SMAF		18, 16
#define	FCH_PM_R_STPCLKSMAF_F_VFSMAF		14, 12
#define	FCH_PM_R_STPCLKSMAF_F_C3SMAF		10, 8
#define	FCH_PM_R_STPCLKSMAF_F_C2SMAF		6, 4
#define	FCH_PM_R_STPCLKSMAF_F_S4S5SMAF		2, 0
#define	FCH_PM_R_STPCLKSMAF_V_C2_STOP_GRANT	0
#define	FCH_PM_R_STPCLKSMAF_V_C3_SLEEP		1
#define	FCH_PM_R_STPCLKSMAF_V_C0_FID_CHANGE	2
#define	FCH_PM_R_STPCLKSMAF_V_S1_POS		3
#define	FCH_PM_R_STPCLKSMAF_V_S3_STR		4
#define	FCH_PM_R_STPCLKSMAF_V_C0_THROTTLE	5
#define	FCH_PM_R_STPCLKSMAF_V_S45_STD_SOFF	6
#define	FCH_PM_R_STPCLKSMAF_V_C1_HALT		7

#define	FCH_PM_R_PWRRSTCFG_OFFSET		0x10
#define	FCH_PM_R_PWRRSTCFG_WIDTH		16
#define	FCH_PM_R_PWRRSTCFG_F_FATALRSTTOS5RST	6, 6
#define	FCH_PM_R_PWRRSTCFG_F_RTCCLKCHKEN_S5REG	5, 5
#define	FCH_PM_R_PWRRSTCFG_F_SLPS3WAITRSTASRT	4, 4
#define	FCH_PM_R_PWRRSTCFG_F_RSTBLKSEL_1_0	3, 2
#define	FCH_PM_R_PWRRSTCFG_F_RSTBLKSEL_1_0_V_OLD	0
#define	FCH_PM_R_PWRRSTCFG_F_RSTBLKSEL_1_0_V_NEW_S0I3	1
#define	FCH_PM_R_PWRRSTCFG_F_RSTBLKSEL_1_0_V_NEW2	2
#define	FCH_PM_R_PWRRSTCFG_F_RSTBLKSEL_1_0_V_NEW3	3
#define	FCH_PM_R_PWRRSTCFG_F_RTCCLKCHKEN_S5REG_V_DIS	0
#define	FCH_PM_R_PWRRSTCFG_F_RTCCLKCHKEN_S5REG_V_STRAP	1
#define	FCH_PM_R_PWRRSTCFG_F_TOGGLEALLPWRGOODONCF9	1, 1
#define	FCH_PM_R_PWRRSTCFG_F_TOGGLEPG1APG2PGXHCONCF9	0, 0

#define	FCH_PM_R_FCHPWRGOODTMR_OFFSET		0x12
#define	FCH_PM_R_FCHPWRGOODTMR_WIDTH		16
#define	FCH_PM_R_FCHPWRGOODTMR_F_FCHPWRGOODTMR	10, 0	/* XXX units */

#define	FCH_PM_R_PGPWRGOODTOALLENTMR_OFFSET	0x14
#define	FCH_PM_R_PGPWRGOODTOALLENTMR_WIDTH	16
#define	FCH_PM_R_PGPWRGOODTOALLENTMR_F_PGPWRGOODTOALLENTMR	10, 0

#define	FCH_PM_R_PGPWRGOODASSERTIONTMR_OFFSET	0x16
#define	FCH_PM_R_PGPWRGOODASSERTIONTMR_WIDTH	16
#define	FCH_PM_R_PGPWRGOODASSERTIONTMR_F_PGPWRGOODASSERTIONTMR	10, 0

#define	FCH_PM_R_PWRGATETMR_OFFSET		0x18
#define	FCH_PM_R_PWRGATETMR_WIDTH		32
#define	FCH_PM_R_PWRGATETMR_F_PWRISLANDDAUGHTERASSERTIONTMR	31, 28
#define	FCH_PM_R_PWRGATETMR_F_PWRISLANDMOTHERASSERTIONTMR	27, 24
#define	FCH_PM_R_PWRGATETMR_F_PWRISLANDMEMDAUGHTERASSERTIONTMR	23, 20
#define	FCH_PM_R_PWRGATETMR_F_PWRISLANDMEMMOTHERASSERTIONTMR	19, 16
#define	FCH_PM_R_PWRGATETMR_F_PWRISLANDMEMMOTHERDEASSERTIONTMR	15, 12
#define	FCH_PM_R_PWRGATETMR_F_PWRISLANDMEMDAUGHTERDEASSERTIONTMR 11, 8
#define	FCH_PM_R_PWRGATETMR_F_PWRISPANDMOTHERDEASSERTIONTMR	7, 4
#define	FCH_PM_R_PWRGATETMR_F_PWRISLANDDAUGHTERDEASSERTIONTMR	3, 0

#define	FCH_PM_R_PLLRSTBTMR_OFFSET		0x1c
#define	FCH_PM_R_PLLRSTBTMR_WIDTH		16
#define	FCH_PM_R_PLLRSTBTMR_F_PLLRSTBTMR	10, 0	/* XXX units */

#define	FCH_PM_R_PLLLOCKTMR_OFFSET		0x1e
#define	FCH_PM_R_PLLLOCKTMR_WIDTH		16
#define	FCH_PM_R_PLLLOCKTMR_F_PLLLOCKTMR	10, 0	/* XXX units */

#define	FCH_PM_R_PCIRSTBTMR_OFFSET		0x20
#define	FCH_PM_R_PCIRSTBTMR_WIDTH		16
#define	FCH_PM_R_PCIRSTBTMR_F_PCIRSTBTMR	10, 0	/* XXX units */

#define	FCH_PM_R_CPURSTBTMR_OFFSET		0x22
#define	FCH_PM_R_CPURSTBTMR_WIDTH		16
#define	FCH_PM_R_CPURSTBTMR_F_CPURSTBTMR	10, 0	/* XXX units */

#define	FCH_PM_R_NBPWRGOODTMR_OFFSET		0x24
#define	FCH_PM_R_NBPWRGOODTMR_WIDTH		16
#define	FCH_PM_R_NBPWRGOODTMR_F_NBPWRGOODTMR	10, 0	/* XXX units */

#define	FCH_PM_R_CPUPWRGOODTMR_OFFSET		0x26
#define	FCH_PM_R_CPUPWRGOODTMR_WIDTH		16
#define	FCH_PM_R_CPUPWRGOODTMR_F_CPUPWRGOODTMR	10, 0	/* XXX units */

#define	FCH_PM_R_S0TOS5ENTMR_OFFSET		0x28
#define	FCH_PM_R_S0TOS5ENTMR_WIDTH		16
#define	FCH_PM_R_S0TOS5ENTMR_F_S0TOS5ENTMR	10, 0	/* XXX units */

#define	FCH_PM_R_S5TOS0ENTMR_OFFSET		0x2a
#define	FCH_PM_R_S5TOS0ENTMR_WIDTH		16
#define	FCH_PM_R_S5TOS0ENTMR_F_S5TOS0ENTMR	10, 0	/* XXX units */

#define	FCH_PM_R_SLPRSTTMR_OFFSET		0x2c
#define	FCH_PM_R_SLPRSTTMR_WIDTH		16
#define	FCH_PM_R_SLPRSTTMR_F_SLPRSTTMR		10, 0	/* XXX units */

#define	FCH_PM_R_OVERRIDEDEVRSTTMRTMR_OFFSET	0x2e
#define	FCH_PM_R_OVERRIDEDEVRSTTMRTMR_WIDTH	16
#define	FCH_PM_R_OVERRIDEDEVRSTTMRTMR_F_OVERRIDERSTBTMR	11, 8
#define	FCH_PM_R_OVERRIDEDEVRSTTMRTMR_F_OVERRIDEREFCLKOKTMR	7, 4
#define	FCH_PM_R_OVERRIDEDEVRSTTMRTMR_F_OVERRIDEPWRRSTBTMR	3, 0

#define	FCH_PM_R_OVERRIDEPWRRSTBASRTTMR_OFFSET	0x30
#define	FCH_PM_R_OVERRIDEPWRRSTBASRTTMR_WIDTH	16
#define	FCH_PM_R_OVERRIDEPWRRSTBASRTTMR_F_OVERRIDEPWRRSTBASRTTMR 10, 0

#define	FCH_PM_R_OVERRIDEREFCLKOKDSRTTMR_OFFSET	0x32
#define	FCH_PM_R_OVERRIDEREFCLKOKDSRTTMR_WIDTH	16
#define	FCH_PM_R_OVERRIDEREFCLKOKDSRTTMR_F_OVERRIDEREFCLKOKDSRTTMR 10, 0

/*
 * XXX The next 2 registers are per-device bitmaps; the assignment of
 * devices to bits is unknown but appears to be identical to AOAC.
 */
#define	FCH_PM_R_OVERRIDEENABLE_OFFSET		0x34
#define	FCH_PM_R_OVERRIDEENABLE_WIDTH		32

#define	FCH_PM_R_DEVRST_RSTBONLY_OFFSET		0x38
#define	FCH_PM_R_DEVRST_RSTBONLY_WIDTH		32

#define	FCH_PM_R_S0RESETTMR_OFFSET		0x3c
#define	FCH_PM_R_S0RESETTMR_WIDTH		16
#define	FCH_PM_R_S0RESETTMR_F_S0RESETTMR	11, 0	/* XXX units */

#define	FCH_PM_R_PWRRSTCNFG_OFFSET		0x3e
#define	FCH_PM_R_PWRRSTCNFG_WIDTH		16
#define	FCH_PM_R_PWRRSTCNFG_F_ENCPUWAITDEV	0, 0

#define	FCH_PM_R_ESPIINTRCTRL_OFFSET		0x40
#define	FCH_PM_R_ESPIINTRCTRL_WIDTH		32
/*
 * This is a bitmapped field.  Each bit masks off a single IRQ from
 * the ESPI interface (numbers 0 to 23 inclusive).
 */
#define	FCH_PM_R_ESPIINTRCTRL_F_ESPIDEVINTRMASK	23, 0

#define	FCH_PM_R_BOOTTIMEREN_OFFSET		0x44
#define	FCH_PM_R_BOOTTIMEREN_WIDTH		32
#define	FCH_PM_R_BOOTTIMEREN_F_BOOTTMRDISABLE	31, 31
#define	FCH_PM_R_BOOTTIMEREN_F_FAILBOOTRSTSTS	30, 30	/* W1C */
#define	FCH_PM_R_BOOTTIMEREN_F_EXPIREBOOTTMR	29, 29
#define	FCH_PM_R_BOOTTIMEREN_F_BOOTTMRSTOPONGALINK	28, 28
#define	FCH_PM_R_BOOTTIMEREN_F_BOOTTMRFUNCEN	27, 27
#define	FCH_PM_R_BOOTTIMEREN_F_FAILBOOTTIMER	24, 0

#define	FCH_PM_R_PGPWRENDLY_OFFSET		0x48
#define	FCH_PM_R_PGPWRENDLY_WIDTH		32
#define	FCH_PM_R_PGPWRENDLY_F_PG1PWRDOWNDLYTMR	31, 24
#define	FCH_PM_R_PGPWRENDLY_F_XHCPWRENDLYTMR	23, 16
#define	FCH_PM_R_PGPWRENDLY_F_PG2PWRENDLYTMR	15, 8
#define	FCH_PM_R_PGPWRENDLY_F_PG1APWRENDLYTMR	7, 0

#define	FCH_PM_R_I2CINPUTTHRESHOLD_OFFSET	0x4c
#define	FCH_PM_R_I2CINPUTTHRESHOLD_WIDTH	32
#define	FCH_PM_R_I2CINPUTTHRESHOLD_F_GBEPWRENDLYTMR	31, 24
#define	FCH_PM_R_I2CINPUTTHRESHOLD_F_OTGPWRENDLYTMR	23, 16
#define	FCH_PM_R_I2CINPUTTHRESHOLD_F_I2C5INPUTTHRESHOLDHI	5, 5
#define	FCH_PM_R_I2CINPUTTHRESHOLD_F_I2C4INPUTTHRESHOLDHI	4, 4
#define	FCH_PM_R_I2CINPUTTHRESHOLD_F_I2C3INPUTTHRESHOLDHI	3, 3
#define	FCH_PM_R_I2CINPUTTHRESHOLD_F_I2C2INPUTTHRESHOLDHI	2, 2
#define	FCH_PM_R_I2CINPUTTHRESHOLD_F_I2C1INPUTTHRESHOLDHI	1, 1
#define	FCH_PM_R_I2CINPUTTHRESHOLD_F_I2C0INPUTTHRESHOLDHI	0, 0

#define	FCH_PM_R_APUPLLCTRL_OFFSET		0x50
#define	FCH_PM_R_APUPLLCTRL_WIDTH		32
#define	FCH_PM_R_APUPLLCTRL_F_APUPLLRSTBTMR	31, 24
#define	FCH_PM_R_APUPLLCTRL_F_APUPLLRSTBTMR_U_TIME_NS	USEC2NSEC(16)
#define	FCH_PM_R_APUPLLCTRL_F_APUPLLPWRRSTBTMR	23, 16
#define	FCH_PM_R_APUPLLCTRL_F_APUPLLPWRRSTBTMR_U_TIME_NS	USEC2NSEC(16)
#define	FCH_PM_R_APUPLLCTRL_F_APUPLLCTRLEN	0, 0

#define	FCH_PM_R_SERIALIRQCONFIG_OFFSET		0x54
#define	FCH_PM_R_SERIALIRQCONFIG_WIDTH		16
#define	FCH_PM_R_SERIALIRQCONFIG_F_SOFTWAREIRQ12	13, 13
#define	FCH_PM_R_SERIALIRQCONFIG_F_SOFTWAREIRQ1	12, 12
#define	FCH_PM_R_SERIALIRQCONFIG_F_UNDO_SER_IRQ_CHANGE	10, 10
#define	FCH_PM_R_SERIALIRQCONFIG_F_LEGACY_DIS	9, 9
#define	FCH_PM_R_SERIALIRQCONFIG_F_SIRQ_CNTRL	8, 8
#define	FCH_PM_R_SERIALIRQCONFIG_F_SERIALIRQENABLE	7, 7
#define	FCH_PM_R_SERIALIRQCONFIG_F_SERIRQMODE	6, 6
#define	FCH_PM_R_SERIALIRQCONFIG_F_NUMSERIRQBITS	5, 2
#define	FCH_PM_R_SERIALIRQCONFIG_F_NUMSERIRQBITS_OFFS	17
#define	FCH_PM_R_SERIALIRQCONFIG_F_NUMSTARTBITS	1, 0
#define	FCH_PM_R_SERIALIRQCONFIG_F_NUMSTARTBITS_SHL	1
#define	FCH_PM_R_SERIALIRQCONFIG_F_NUMSTARTBITS_OFFS	4

#define	FCH_PM_R_RTCCONTROL_OFFSET		0x56
#define	FCH_PM_R_RTCCONTROL_WIDTH		16
#define	FCH_PM_R_RTCCONTROL_F_EXTRARTCCMOSEN	14, 14
#define	FCH_PM_R_RTCCONTROL_F_ALTCMOSMAPEN	13, 13
#define	FCH_PM_R_RTCCONTROL_F_CENTURYEN		12, 12
#define	FCH_PM_R_RTCCONTROL_F_MASK_RTC_CLK_OUT	11, 11
#define	FCH_PM_R_RTCCONTROL_F_RTCCLKDRIVE	10, 10
#define	FCH_PM_R_RTCCONTROL_F_RTC_TEST_EN	6, 6	/* MBZ */
#define	FCH_PM_R_RTCCONTROL_F_RTCPROTECTC0_CF	4, 4	/* W-once */
#define	FCH_PM_R_RTCCONTROL_F_RTCPROTECTD0_DF	3, 3	/* W-once */
#define	FCH_PM_R_RTCCONTROL_F_RTCPROTECTE0_EF	2, 2	/* W-once */
#define	FCH_PM_R_RTCCONTROL_F_RTCPROTECTF0_FF	1, 1	/* W-once */
#define	FCH_PM_R_RTCCONTROL_F_RTCPROTECT38_3F	0, 0	/* W-once */

#define	FCH_PM_R_VRT_T1_OFFSET			0x58
#define	FCH_PM_R_VRT_T1_WIDTH			8
#define	FCH_PM_R_VRT_T1_U_TIME_NS		MSEC2NSEC(1)

#define	FCH_PM_R_VRT_T2_OFFSET			0x59
#define	FCH_PM_R_VRT_T2_WIDTH			8
#define	FCH_PM_R_VRT_T2_U_TIME_NS		MSEC2NSEC(4)

#define	FCH_PM_R_INTRUDERCONTROL_OFFSET		0x5a
#define	FCH_PM_R_INTRUDERCONTROL_WIDTH		8
#define	FCH_PM_R_INTRUDERCONTROL_F_CMOSERASESYS	6, 6
#define	FCH_PM_R_INTRUDERCONTROL_F_CMOSERASECLR	5, 5
#define	FCH_PM_R_INTRUDERCONTROL_F_CMOSEARSEDIS	4, 4
#define	FCH_PM_R_INTRUDERCONTROL_F_INTRUDERALERTSTS	2, 2
#define	FCH_PM_R_INTRUDERCONTROL_F_INTRUDERALERTCLR	1, 1
#define	FCH_PM_R_INTRUDERCONTROL_F_INTRUDERALERTDIS	0, 0

#define	FCH_PM_R_RTCSHADOW_OFFSET		0x5b
#define	FCH_PM_R_RTCSHADOW_WIDTH		8
#define	FCH_PM_R_RTCSHADOW_F_FORCEPWRON		7, 7
#define	FCH_PM_R_RTCSHADOW_F_POWERSTATE		6, 6
#define	FCH_PM_R_RTCSHADOW_F_PWRFAILOPTION	5, 4
#define	FCH_PM_R_RTCSHADOW_F_PWRFAILOPTION_V_ALW_OFF	0
#define	FCH_PM_R_RTCSHADOW_F_PWRFAILOPTION_V_ALW_ON	1
#define	FCH_PM_R_RTCSHADOW_F_PWRFAILOPTION_V_ALW_OFF2	2
#define	FCH_PM_R_RTCSHADOW_F_PWRFAILOPTION_V_PREVIOUS	3
#define	FCH_PM_R_RTCSHADOW_F_PWRFAILSHADOW	3, 0

#define	FCH_PM_R_RTCGPIO_OFFSET			0x5d
#define	FCH_PM_R_RTCGPIO_WIDTH			8
#define	FCH_PM_R_RTCGPIO_F_ORTCCLKPUB		7, 7
#define	FCH_PM_R_RTCGPIO_F_RTCIRQGPIOENB	1, 1
#define	FCH_PM_R_RTCGPIO_F_RTCIRQGPIOOUT	0, 0

#define	FCH_PM_R_RTCEXTINDEX_OFFSET		0x5e
#define	FCH_PM_R_RTCEXTINDEX_WIDTH		8

#define	FCH_PM_R_RTCEXTDATA_OFFSET		0x5f
#define	FCH_PM_R_RTCEXTDATA_WIDTH		8

#ifdef __cplusplus
}
#endif

#endif /* _SYS_IO_HUASHAN_PMIO_H */
